#!/usr/bin/env bash

set -e

main() {
    stow . && ${BASH_SOURCE[0]} help
}

# @cmd Opens setup for homepage
# @alias home,dashboard
homepage() {
	cd .config/HomePage/config/
	nvim .
}

# @cmd Opens setup for bashrc
# @alias bashrc,bash,conf
config() {
	nvim .bashrc
}

# @cmd Opens setup for neovim
# @alias nvim,vim,vi
neovim() {
	cd .config/nvim/
	nvim .
}

# @cmd Builds and runs a dev envinronment for my dotfiles configuration
dev() {
	docker build . -t arch-bootstrap && x11docker -I -d --sudouser=nopasswd arch-bootstrap
}

# See more details at https://github.com/sigoden/argc
eval "$(start-tool extend)"
eval "$(argc --argc-eval "$0" "$@")"
