---
- File Hosting:
    - Nextcloud:
        icon: nextcloud.png
        href: http://richserver:80
        description: Next cloud file hosting
    - Jellyfin:
        icon: jellyfin.png
        href: http://richserver:8096
        description: Self hosted media streaming
    - Photoprism:
        icon: photoprism.png
        href: http://richserver:2342
        description: High speed quality photos library
    - ActualBudget:
        icon: actual-budget.png
        href: http://richserver:5006
        description: High speed budgeting tool
    - ArchiveBox:
        icon: archivebox.png
        href: http://richserver:8000
        description: Self hosted web archive

- Tools:
    - Jenkins:
        icon: jenkins.png
        href: http://richserver:8080
        description: Task builder utility server
    - LazyDocker:
        icon: docker.png
        href: http://richserver:7682
        description: Docker container management tool
    - Glances:
        icon: glances.png
        href: http://richserver:6125
        description: Top level visualizer system resources

- Development:
    - Gitea:
        icon: gitea.png
        href: http://richserver:3000
        description: Git repository manager
    - ItTools:
        icon: it-tools.png
        href: http://richserver:9889
        description: Collection of handy online tools for developers
    - SearXNG:
        icon: searx.png
        href: http://richserver:6006
        description: Self hosted best search engine

- Entertainment:
    - Navidrome:
        icon: navidrome.png
        href: http://richserver:4533
        description: Self hosted music server
    - Stash:
        icon: stash.png
        href: http://richserver:9999
        description: Owo repository of your stuff
